name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.ACCOUNT_GITHUB_TOKEN }}

      - name: Build and publish NPM packages
        uses: evg4b/goreleaser-npm-publisher-action@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          prefix: '@evg4b'
          description: 🫏 A small utility for batch file rpecessing using AI
          keywords: |-
            processing
            cli
            utility
            ai
            ollama-client
